### ISSUE TITLE
Implement drag-and-drop onto taskbar/dock icon to open document

### ISSUE THREAD

**Issue by michaelrhanson** [mozilla/openwebapps#128]
We should be able to send an event to an application window when the user drags a document to the taskbar/dock.  Optimal flow is probably to open a new window and send the event to it once it is loaded; possible complications are if the app expects to only support a single window, in which case we should send the event to that window.

**Comment by michaelrhanson** [comment]
Note that this should almost certainly be an application of the DOM dataTransfer behavior we already use for drag-and-drop, see https://developer.mozilla.org/en/Using_files_from_web_applications#Selecting_files_using_drag_and_drop

**Comment by ianb** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=703700
