### ISSUE TITLE
appCache does not cache app icon images

### ISSUE THREAD

**Issue by nickdesaulniers** [mozilla/openwebapps#166]
So the app icons are accessed online, and can't be cached via appCache.

Running this code in the console from this url: https://myapps.mozillalabs.com/

``` javascript
// Note: you will probably have to change the images index on the next line
var image = document.images[6];
var canvas = document.createElement('canvas');

canvas.width = image.width;
canvas.height = image.height;

var ctx = canvas.getContext('2d');
ctx.drawImage(image, 0, 0);

var dataURL = canvas.toDataURL();
```

raises an:

`Error: The operation is insecure.`

as specified by: http://www.w3.org/TR/html5/the-canvas-element.html#security-with-canvas-elements

**Comment by ianb** [comment]
Could this be helpful? https://developer.mozilla.org/en/nsIDOMOfflineResourceList#add.28.29

**Comment by nickdesaulniers** [comment]
Nice find, but you're five minutes late to the party.  Bill Walker showed me this yesterday.  I don't want to spoil the surprise, but you should watch my presentation later today to see how mozAdd works, and doesn't. ;)

**Comment by ianb** [comment]
FWIW, there's also an https mixed content problem with the current icon approach, so there might be enough reason to do proxying which would also probably offer a solution to this problem.

**Comment by nickdesaulniers** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=767260
