### ISSUE TITLE
add post-installation feedback in app directory

### ISSUE THREAD

**Issue by lloyd** [mozilla/openwebapps#22]
when a user installs an application through the app directory, it's unclear what to do next.

To understand, install an application from here: https://apps.mozillalabs.com/appdir/

Perhaps some feedback immediately after installation pointing the user at the app dashboard?  Something in the vein of what's done at http://appmanifest.org?

**Comment by ianb** [comment]
For reference, the Chrome Store opens the homepage (in a new tab) and the new app icon fades in.

**Comment by lloyd** [comment]
done.
