### ISSUE TITLE
FFX addon not working on OpenSuSE 11.3 64bit

### ISSUE THREAD

**Issue by lloyd** [mozilla/openwebapps#25]
Here's a report from a user:
- When I install the plugin, the black gearwheel appears to the right of
  the search box as I presume it should...but on my OpenSuSE 11.3 64bit
  machine, clicking on the gearwheel produces a very brief flash of a
  black panel just below the gearwheel - then nothing.

**Comment by anantn** [comment]
Ah, yes I am able to reproduce this bug. It occurs because you currently have no installed apps -- if I try installing a couple from https://apps.mozillalabs.com/appdir/ the panel appears again.

**Comment by SteveBaker** [comment]
Sorry - I disagree with your diagnosis.

Even with either one or two or even as many as eight Apps installed, it still happens maybe 80% of the time...I should have mentioned that I'm running Minefield nightlies and I updated just now before trying again so I'm on 4.0b13pre(2011-03-03).
.

When it does pop up, I only see that portion of the black box, icons, etc that is within the Firefox GUI area - everything that should drop down over the current web page is missing.

**Comment by anantn** [comment]
We are reworking the add-on to make it restartless and will be making more changes. Will revisit this issue when the next version is released.

**Comment by ianb** [comment]
Probably obsolete; reopen on Bugzilla if not
