### ISSUE TITLE
calling navigator.apps.install with relative url sets app "origin" to "undefined://"

### ISSUE THREAD

**Issue by dmose** [mozilla/openwebapps#27]
Here's an example:

```
navigator.apps.install({
  url: "theband.webapp",
  onsuccess: function() {
    alert('OMG');
  },
  onerror: function(wtf) {
    console.log(wtf);
  }
```

Doing this results in the app manifest being retrieved properly and the app being installed, but once installed, if the user goes to the gear icon in Firefox's browser chrome and selects "Manage Apps", then "View Manifest" for the installed app, the "origin" key of the manifest is set to `undefined://`.

To work around this, we changed the `url` key to be an absolute URL.

**Comment by anantn** [comment]
https://developer.mozilla.org/en/OpenWebApps/The_JavaScript_API#Installation_API_%28navigator.apps.*%29 specifies that the install URL must be absolute (or preceded by a '/' if the app is from the same origin). It seems like we may not be enforcing the rule, we should make the install function fail in this case.

**Comment by dmose** [comment]
Ah, indeed.  We were working off of the less comprehensive doc at https://developer.mozilla.org/en/OpenWebApps/Getting_Started.

**Comment by ianb** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=703714
