### ISSUE TITLE
introduce a maximum size for manifest elements

### ISSUE THREAD

**Issue by lloyd** [mozilla/openwebapps#3]
specifically, name and description could use a specified maximum size, validator and tests should be updated accordingly.

**Comment by ianb** [comment]
I see two options for this:
- Reasonable defaults, which sometimes might be annoyingly short (e.g., 60 character name, 400 character description)
- Just avoid crazy long records with a very liberal limit (e.g., 512 character name, 4k description), but give UAs the option of truncating the fields as they wish, with some more conservative recommended length.

**Comment by lloyd** [comment]
I'll sell ya 128bytes and 1k ?

**Comment by ianb** [comment]
fine by me

**Comment by lloyd** [comment]
impose limits on size of name and description in manifest.  Closed by 104d68f4475a1a11aceffe381aa15a9a4b0b2964
