### ISSUE TITLE
add smoothtransition service for apps

### ISSUE THREAD

**Issue by benadida** [mozilla/openwebapps#36]
this will allow an app to receive a new URL that a user clicks on and have that app transition appropriately.

(It's not clear this is the behavior we want, but we're going to try it.)

**Comment by benadida** [comment]
let's discuss this one, Anant, when you have a chance.

**Comment by benadida** [comment]
this should include the detection of new tab opening and delivery of new messages to it. I'm close to figuring out what this looks like for the login() message, this should be the same here.

**Comment by anantn** [comment]
https://github.com/mozilla/openwebapps/commit/af399f74a08c72579f1adf69a40bafce89c4b47e does the detection part, delivery of the message remains to be implemented.

**Comment by benadida** [comment]
Anant: let's talk about this first thing Friday morning, the content script is unable to call navigator.apps, so we'll probably have to make the faker do some evil chrome-privileged stuff if we really want it to be able to register event handlers.
