### ISSUE TITLE
Get the unit test system back in place

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/openwebapps#38]
See what is broken, what can be automated, what can be pushed, figure out what the interface is, and where we can go.

**Comment by shane-tomlinson** [comment]
So far, what is broken in HTML5 mode (openwebapps not installed):
- typed-storage.html - eventmixin.js and typed-storage.js are missing
- conduits.html - There is no Conduits anywhere.

**Comment by shane-tomlinson** [comment]
Using the openwebapps plugin, the following is broken:
- conduits.html - URLParse is not defined
- typed-storage.html - eventmixin.js and typed-storage.js are missing
- repo_api.html - navigator.apps.invokeService timing out, navigator.apps.install timing out, "use a backchannel to get the pushed image" not passing image back, it is passing null.

**Comment by shane-tomlinson** [comment]
In TypedStorage, many unit tests are expecting the API to return results in a synchronous fashion, but the API itself is async.  Even within the API code, sometimes it asks for things synchronously.

**Comment by shane-tomlinson** [comment]
Need to change all of the TypedStorage to be async.  Tests need updated as well.

**Comment by shane-tomlinson** [comment]
Adding an index.html file that will be an easy way for developers to run any tests in the browser.

**Comment by anantn** [comment]
As far as the add-on goes, only the repo_api tests are relevant, all other components should be tested via the Jetpack infrastructure. We can fix the TypedStorage tests (for the HTML5 repo implementation) at some point but is probably not a super high priority.

**Comment by shane-tomlinson** [comment]
A basic test system is now in place, though still heavily in development.  In the directory /site/tests/ there is a node script, run.js, start this.  Then, go to http://127.0.0.1:60172/tests/index.html, where you can select from a list of tests to run.  These tests should run using both the openwebapps add on, as well as in browsers that do not use this.

**Comment by shane-tomlinson** [comment]
The test "Installation of that same app, from its own origin" in repo_api.html is failing, the iframe that it is opening is too small to work with.

**Comment by shane-tomlinson** [comment]
Start to get a JSLinter going, Lloyd suggests JSHint.

**Comment by shane-tomlinson** [comment]
Start to write tests for the new navigator.apps.\* functions.

**Comment by shane-tomlinson** [comment]
Start to write unit tests for the JetPack only portion of the code.

**Comment by shane-tomlinson** [comment]
Since the basic system is now in place, I will close this and open separate issues for each individual item.
