### ISSUE TITLE
default_locale should be optional

### ISSUE THREAD

**Issue by lloyd** [mozilla/openwebapps#4]
currently default_locale is a required field.  Given that the only other required field is name, it seems someone silly.

proposal is to make default_locale optional except when the locales map is present.  This way a simple manifest stays simple, but once a developer goes to do l10n, the locales dependency on default_locale will help the validator help them understand how l10n is intended to work.

**Comment by ianb** [comment]
The API I roughly imagine for getting a localized manifest would be like localize_manifest(manifest, [best_locale, second_best_locale, ...]) returning something like [actual_locale, manifest].  But the actual locale may not be any locale you requested, if none of them are available.  In the case where the `"locales"` key is not present you'll always get back `"default_locale"`, and it seems relatively unimportant what locale that is.

Writing that out, I guess an advantage to requiring `default_locale` is that if the application wants to pass the locale on somehow (e.g., translate it, mark it up with the lang attribute, etc) then it can, while a null locale is ambiguous.

**Comment by lloyd** [comment]
only require default_locale when locales is present, Closed by 8d3d66f039d0292ee72255556e4b5950f7d46d1f
