### ISSUE TITLE
figure out a "confirm purchase and buy" single-click flow

### ISSUE THREAD

**Issue by benadida** [mozilla/openwebapps#41]

**Comment by benadida** [comment]
Proposed flow:
- link rel in header points to preferred store
- store must offer the "store" activity, so it can be queried for "information for app at this origin"
- OWA popup shows price and identity of app, confirm button or login button depending on whether user is logged in or not.
- one-click "buy"
- leads to buy OWA service call to store
- store does what it needs to do to install the app
- done

**Comment by benadida** [comment]
a non-goal is implementing the actual payment provisioning, since that will likely be rebuilt on existing payment systems.

**Comment by ianb** [comment]
Payment flow has been spec'd out I believe (reopen on Bugzilla if necessary)
