### ISSUE TITLE
define navigator.apps API for doing service invocation

### ISSUE THREAD

**Issue by benadida** [mozilla/openwebapps#42]
Whatever the implementation is (jschannel, direct API injection, etc...), the approach for an OWA to register for certain services should be something like:

```
navigator.apps.services.registerHandler('login', 'doLogin', function(credentials, return_cb) {
   // do something

   // return the result
   result_cb({...});
})
```

**Comment by anantn** [comment]
Are there particular use-cases you have in mind for allowing an app to dynamically register a service handler using such a mechanism? If so, why can they not be fulfilled by static declarations in the manifest?

**Comment by benadida** [comment]
anant: sorry, I didn't mean dynamically register a service handler, I mean simply point to the function that fulfills the actual service. In particular, providing the "login" service might mean you provide both "doLogin" and "doLogout" or something like that, and rather than ask apps to set up the JSchannel themselves, I figure it's easier for them to have a nice JS API to register their functions.

**Comment by anantn** [comment]
Hmm, I'm not so sure that this is the cleanest approach. When would the app call registerHandler(): at the endpoint when it is loaded in the iframe or prior to it? What is the lifetime of the binding?

I agree we need to make it easier for the developer by allowing them to just write functions and not worry about postMessage, we tried to make this work in our initial version but could not access the iframe's functions directly (and definitely cannot in Jetpack). We can write a wrapper around JSChannel to implement a sort of RPC to make this work.

Why not have the developer specify the function name (as an optional property) in the manifest itself? That way everything is in one place -- feels a little more cleaner to me:

```
"experimental": {
  "services": {
      "image.send": {
           "endpoint": "/services/image-send",
           "method": "doSend"
      }
}
```

**Comment by benadida** [comment]
Anant: I'm envisioning that the app does something like this:

```
navigator.apps.services.registerHandler(...);
navigator.apps.services.registerHandler(...);
```

and then

```
navigator.apps.ready();
```

or something to that effect. So I think the loading timing is actually fairly trivial.

Specifying JS function names in manifest.... I don't think that's cleaner, I think that ties down the developer in an unnecessary way.

Of course, registerHandler might very well just be a wrapper around JSChannel. But isn't it nice that we can change that?

**Comment by shane-tomlinson** [comment]
From an end developers point of view, I see the registerHandler as being cleaner and more flexible - I have always hated declaring global scope function names for similar purposes - something about it feels dirty.  On the other hand, unless there are plans to keep all apps loaded in memory at once, I also see the need for a manifest to declare which services an app makes available.  This is so that the service request manager can look through the list of app manifests, see which apps provide the requested service, and load appropriately.

Could it be a combination of the two, where in the services section, it is something along the lines of:

```
"experimental": {
   "services": {
      "image.send": {
           "endpoint": "/services/image-send"
      }
}
```

and then within "/services/image-send", there is a call to

```
navigator.apps.services.registerHandler("image.send", ...);
```

From the above example, I am not sure which fields other than endpoint are needed, perhaps even that could be left out and it compresses to:

```
"experimental": {
   "services": {
      "image.send": "/services/image-send"
   }
}
```

**Comment by benadida** [comment]
Shane: yes, we definitely keep the list of services in the manifest, I'm not suggesting otherwise. I'm only suggesting the hooks be .. hooked I guess in the JS API call.

Sometimes we need more variables, so I prefer the former.

**Comment by anantn** [comment]
Calling registerHandler() from an endpoint should succeed only for the service type it previously registered itself for in the manifest. services.ready() is a good idea to initiate the handshake between endpoint and mediator. Let's do it!

**Comment by benadida** [comment]
implemented and committed, though login needs some more work, I'll open another issue.
