### ISSUE TITLE
hide bookmarks bar on app tab?

### ISSUE THREAD

**Issue by benadida** [mozilla/openwebapps#45]
By default, bookmark bar is not shown, but if user turns it on, should we forcefully hide it in app tabs? Probably, but needs discussion.

**Comment by benadida** [comment]
Ragavan says "override" enthusiastically :)

**Comment by anantn** [comment]
User research group might help us out here. I've seen some folks use their bookmarks bar as some sort of 'quick launch' panel, so you're in your app and you want to go somewhere else, it's a one click operation (sort of like a mini-dashboard?).

**Comment by ianb** [comment]
I believe this is defunct with Native Apps.  (If not, please reopen on Bugzilla)
