### ISSUE TITLE
Close notification panel after selecting an app or manage apps

### ISSUE THREAD

**Issue by whimboo** [mozilla/openwebapps#48]
When you open the notificiation panel by clicking the webapps button in the toolbar, and selecting an app or click on manage apps, the notification doesn't close. In nearly all the cases the user wants to directly switch to an application or to about:apps, and doesn't need that panel anymore right after. Currently it's in the way and annoying that you have to close it yourself.

**Comment by ianb** [comment]
The panel has been removed
