### ISSUE TITLE
Prepare docs on how to add tests for MozMill/DocTestJS based tests.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/openwebapps#58]

**Comment by ianb** [comment]
If there's anything I can do to help with automating the doctest.js stuff, ping me (right now it vaguely attempts QUnit markup on success/failure).

**Comment by shane-tomlinson** [comment]
Thanks Ian, I am still trying to find a good solution to pass on to QA, they aren't keen on having test logic outside of MozMill based scripts.
