### ISSUE TITLE
describe whitespace meaning in description and name

### ISSUE THREAD

**Issue by ianb** [mozilla/openwebapps#6]
Right now the description is just "human readable", but there's no indication about how newlines or multiple spaces should be handled.

I recommend:
- The name is a single-line, and all whitespace is normalized to one space (i.e., newlines are equivalent to a space).
- The description can contain newlines and whitespace, and both are preserved when displayed.  That means in the HTML case that newlines are replaced with `<br>` and multiple spaces use `&nbsp;`.  This allows, for example, simple indented lists.

**Comment by lloyd** [comment]
I like your proposal for name, but think we should do the same for description.  My thinking is that if you support overly simple markup, you constrain the display of information without providing any real expressive power.  I think we should say description is a chunk of unbroken prose, and in doing so we give a lil' bit more structure and freedom to the folks designing the UA integration.  

just a hunch.

**Comment by ianb** [comment]
Android apps, from what I can tell, have a screenshot and a plaintext description.  The description is frequently more than one paragraph, and includes bullet points.  This seems reasonable to me.

**Comment by ianb** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=703716
