### ISSUE TITLE
apps API function calls are inconsistent between navigator.apps and navigator.apps.mgmt.* 

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/openwebapps#62]
In navigator.apps.\* functions, we use objects with named members for the only parameter, eg:

```
navigator.apps.install({
   url: 'some.url.here',
   onsuccess: function(data) { /* do some awesomeness here */
   onfailure: function(data) { /* uh oh */
});
```

vs

```
navigator.apps.mgmt.uninstall( 'some.url.here', 
     function() { /* all good */ }, 
     function() { /* bad jiji */ } 
);
```

I propose that we unify these to use objects with named members universally, the primary advantages being a consistent interface as well as being able to add parameters at a later date without affecting the interface.

**Comment by ianb** [comment]
One argument I remember against named parameters was that it was hard to specify the signatures using WebIDL, and I think generally more of a nuisance to implement in C++.  Which is by no means a solid reason, but it was some of what informed the change of some APIs to not be named parameters.

**Comment by ghost** [comment]
I can't think of any valid objection. :)

Regards,
Dan Walkowski

**Comment by ianb** [comment]
Everything is consistently using positional parameters now
