### ISSUE TITLE
OWA interaction buttons need IDs for testing.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/openwebapps#65]
Buttons in doorhangers, request panels, etc in both the OWA addon and HTML5 shim need IDs so that testing frameworks can find these elements without resorting to XPATH.  XPATH is brittle in the fact that if the element changes locations within the browser or page, the elements are no longer found.

**Comment by ianb** [comment]
I'll let @dclarke or @mdabbagh reopen on Bugzilla if this is still valid.
