### ISSUE TITLE
Pop-up is cut-off when add-on bar is not enabled

### ISSUE THREAD

**Issue by sriramramani** [mozilla/openwebapps#68]
When the add-on bar is not enabled, the popup to add a webapp appears on the bottom left corner. A part of it remains closed. In such cases when the add on bar is not enabled, I feel, it would be better to show the popup with an arrow pointing to the favicon.

**Comment by ianb** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=703705
