### ISSUE TITLE
openwebapp faker causes 404 at fivethirtyeight.blogs.nytimes.com

### ISSUE THREAD

**Issue by wfwalker** [mozilla/openwebapps#80]
When the openwebapps faker offers the chance to add an app for subdomains of nytimes.com, it can cause a 404.
1. go to nytimes.com, add app when offered
2. navigate to http://fivethirtyeight.blogs.nytimes.com/
3. you will be offered the chance to add nytimes app again
4. the second app in your tray will go to http://fivethirtyeight.blogs.nytimes.com/skimmer which does not exist

**Comment by ianb** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=703704
